### ISSUE TITLE
Update repository description

### ISSUE THREAD

**Issue by afuetterer** [rdmorganiser/.github#4]
Please update the repository description to:

`Community health files for the [@rdmorganiser](https://github.com/rdmorganiser) organization`

**Comment by MyPyDavid** [comment]
community health :) https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file

**Comment by afuetterer** [comment]
Oh, GitHub autolinks to the Org.

I guess you only need 
`Community health files for the @rdmorganiser organization`
